### PR TITLE
Add maintainers

### LINKED ISSUE #2: Add maintainers
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
At the moment, a single maintainer is listed for this package. To address [the infamous bus factor](https://en.wikipedia.org/wiki/Bus_factor) we should add a few more willing maintainers.

### PR DESCRIPTION
**Pull request by zklaus**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #2

### CODE REVIEW

**Comment by zklaus** [comment]
@valeriupredoi, @nielsdrost, @jvegasbsc, @bouweandela could you guys signal your approval to be added here please?

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by jvegreg** [comment]
Yes , of course

**Comment by bouweandela** [comment]
Thanks, that would be great!

**Comment by valeriupredoi** [comment]
the Force is strong with you @zklaus - cheers, man :beer:

**Pull request merged**
